// Auto-generated by scripts/generate-company-tags.js
window.DSA_GRIND_COMPANIES = {
  "contiguous-array": [
    "Meta",
    "Amazon"
  ],
  "add-binary": [
    "Meta",
    "Amazon"
  ],
  "corporate-flight-bookings": [
    "Amazon",
    "Google"
  ],
  "all-oone-data-structure": [
    "Amazon",
    "Google"
  ],
  "count-primes": [
    "Amazon",
    "Microsoft"
  ],
  "add-digits": [
    "Amazon"
  ],
  "design-browser-history": [
    "Amazon",
    "Google"
  ],
  "design-hashmap": [
    "Amazon",
    "Google"
  ],
  "design-circular-queue": [
    "Amazon",
    "Google"
  ],
  "first-missing-positive": [
    "Amazon",
    "Google"
  ],
  "design-linked-list": [
    "Amazon",
    "Microsoft"
  ],
  "design-hashset": [
    "Amazon",
    "Google"
  ],
  "contains-duplicate": [
    "Amazon",
    "Apple"
  ],
  "detect-squares": [
    "Amazon",
    "Google"
  ],
  "contains-duplicate-ii": [
    "Amazon",
    "Google"
  ],
  "degree-of-an-array": [
    "Amazon"
  ],
  "group-anagrams": [
    "Amazon",
    "Meta",
    "Uber"
  ],
  "first-unique-character-in-a-string": [
    "Amazon",
    "Bloomberg"
  ],
  "find-the-index-of-the-first-occurrence-in-a-string": [
    "Amazon",
    "Microsoft"
  ],
  "compare-version-numbers": [
    "Microsoft",
    "Amazon"
  ],
  "largest-odd-number-in-string": [
    "Amazon"
  ],
  "custom-sort-string": [
    "Meta",
    "Amazon"
  ],
  "length-of-last-word": [
    "Amazon"
  ],
  "text-justification": [
    "Google",
    "Amazon"
  ],
  "backspace-string-compare": [
    "Meta",
    "Amazon"
  ],
  "3sum": [
    "Meta",
    "Amazon"
  ],
  "intersection-of-two-linked-lists": [
    "Amazon",
    "Microsoft"
  ],
  "3sum-closest": [
    "Amazon"
  ],
  "is-subsequence": [
    "Amazon",
    "Google"
  ],
  "4sum": [
    "Amazon",
    "Adobe"
  ],
  "binary-subarrays-with-sum": [
    "Amazon",
    "Google"
  ],
  "count-number-of-nice-subarrays": [
    "Amazon"
  ],
  "minimum-window-substring": [
    "Amazon",
    "Meta"
  ],
  "find-all-anagrams-in-a-string": [
    "Amazon",
    "Google"
  ],
  "fruit-into-baskets": [
    "Google",
    "Amazon"
  ],
  "maximum-average-subarray-i": [
    "Amazon",
    "Google"
  ],
  "132-pattern": [
    "Amazon",
    "Google"
  ],
  "baseball-game": [
    "Amazon",
    "Google"
  ],
  "add-two-numbers-ii": [
    "Amazon",
    "Microsoft"
  ],
  "asteroid-collision": [
    "Amazon",
    "Google"
  ],
  "basic-calculator": [
    "Google",
    "Amazon"
  ],
  "car-fleet": [
    "Google",
    "Amazon"
  ],
  "add-two-numbers": [
    "Amazon",
    "Microsoft"
  ],
  "merge-two-sorted-lists": [
    "Amazon",
    "Apple"
  ],
  "copy-list-with-random-pointer": [
    "Amazon",
    "Meta"
  ],
  "delete-node-in-a-linked-list": [
    "Apple",
    "Amazon"
  ],
  "reverse-nodes-in-k-group": [
    "Amazon",
    "Microsoft"
  ],
  "insertion-sort-list": [
    "Amazon",
    "Microsoft"
  ],
  "remove-duplicates-from-sorted-list": [
    "Amazon",
    "Microsoft"
  ],
  "capacity-to-ship-packages-within-d-days": [
    "Amazon",
    "Google"
  ],
  "arranging-coins": [
    "Amazon"
  ],
  "find-first-and-last-position-of-element-in-sorted-array": [
    "Amazon",
    "Meta"
  ],
  "find-k-closest-elements": [
    "Amazon",
    "Google"
  ],
  "binary-search": [
    "Amazon",
    "Google"
  ],
  "find-minimum-in-rotated-sorted-array": [
    "Amazon",
    "Microsoft"
  ],
  "median-of-two-sorted-arrays": [
    "Amazon",
    "Google"
  ],
  "01-matrix": [
    "Google",
    "Amazon"
  ],
  "average-of-levels-in-binary-tree": [
    "Amazon",
    "Meta"
  ],
  "all-nodes-distance-k-in-binary-tree": [
    "Amazon",
    "Meta"
  ],
  "all-paths-from-source-to-target": [
    "Amazon",
    "Google"
  ],
  "balanced-binary-tree": [
    "Amazon"
  ],
  "amount-of-time-for-binary-tree-to-be-infected": [
    "Amazon"
  ],
  "binary-tree-maximum-path-sum": [
    "Meta",
    "Amazon"
  ],
  "as-far-from-land-as-possible": [
    "Amazon",
    "Google"
  ],
  "binary-search-tree-iterator": [
    "Meta",
    "Amazon"
  ],
  "binary-tree-inorder-traversal": [
    "Amazon",
    "Microsoft"
  ],
  "binary-tree-level-order-traversal": [
    "Amazon",
    "Microsoft"
  ],
  "binary-tree-level-order-traversal-ii": [
    "Amazon",
    "Microsoft"
  ],
  "design-add-and-search-words-data-structure": [
    "Meta",
    "Amazon"
  ],
  "concatenated-words": [
    "Amazon",
    "Google"
  ],
  "implement-trie-prefix-tree": [
    "Amazon",
    "Google"
  ],
  "design-twitter": [
    "Amazon",
    "Twitter"
  ],
  "find-median-from-data-stream": [
    "Amazon",
    "Google"
  ],
  "find-k-pairs-with-smallest-sums": [
    "Amazon",
    "Google"
  ],
  "kth-largest-element-in-a-stream": [
    "Amazon",
    "Meta"
  ],
  "furthest-building-you-can-reach": [
    "Amazon",
    "Google"
  ],
  "k-closest-points-to-origin": [
    "Meta",
    "Amazon"
  ],
  "accounts-merge": [
    "Meta"
  ],
  "cheapest-flights-within-k-stops": [
    "Amazon",
    "Google"
  ],
  "alien-dictionary": [
    "Amazon",
    "Airbnb"
  ],
  "course-schedule": [
    "Amazon",
    "Meta"
  ],
  "course-schedule-ii": [
    "Amazon",
    "Google"
  ],
  "find-if-path-exists-in-graph": [
    "Amazon",
    "Google"
  ],
  "evaluate-division": [
    "Google",
    "Meta"
  ],
  "find-eventual-safe-states": [
    "Amazon",
    "Google"
  ],
  "critical-connections-in-a-network": [
    "Amazon",
    "Google"
  ],
  "beautiful-arrangement": [
    "Amazon",
    "Google"
  ],
  "combination-sum": [
    "Amazon"
  ],
  "n-queens": [
    "Amazon",
    "Google"
  ],
  "combination-sum-ii": [
    "Amazon",
    "Microsoft"
  ],
  "combination-sum-iii": [
    "Amazon",
    "Google"
  ],
  "combinations": [
    "Google",
    "Amazon"
  ],
  "arithmetic-slices": [
    "Amazon",
    "Google"
  ],
  "best-time-to-buy-and-sell-stock-iii": [
    "Amazon",
    "Microsoft"
  ],
  "best-time-to-buy-and-sell-stock-with-cooldown": [
    "Amazon",
    "Google"
  ],
  "best-time-to-buy-and-sell-stock-with-transaction-fee": [
    "Amazon",
    "Google"
  ],
  "coin-change": [
    "Amazon",
    "Adobe",
    "Google"
  ],
  "best-time-to-buy-and-sell-stock-iv": [
    "Amazon",
    "Microsoft"
  ],
  "coin-change-ii": [
    "Amazon",
    "Google"
  ],
  "combination-sum-iv": [
    "Amazon",
    "Google"
  ],
  "two-sum": [
    "Amazon",
    "Google"
  ],
  "valid-anagram": [
    "Amazon",
    "Bloomberg"
  ],
  "linked-list-cycle": [
    "Amazon",
    "Microsoft"
  ],
  "lru-cache": [
    "Amazon",
    "Microsoft",
    "Google"
  ],
  "min-stack": [
    "Amazon",
    "Microsoft",
    "Bloomberg"
  ],
  "container-with-most-water": [
    "Amazon",
    "Google"
  ],
  "trapping-rain-water": [
    "Google",
    "Amazon"
  ],
  "remove-nth-node-from-end-of-list": [
    "Amazon",
    "Meta"
  ],
  "valid-palindrome": [
    "Meta",
    "Amazon"
  ],
  "longest-substring-without-repeating-characters": [
    "Amazon",
    "Adobe"
  ],
  "valid-parentheses": [
    "Amazon",
    "Meta"
  ],
  "largest-rectangle-in-histogram": [
    "Amazon",
    "Google"
  ],
  "daily-temperatures": [
    "Amazon",
    "Google"
  ],
  "search-in-rotated-sorted-array": [
    "Amazon",
    "Meta"
  ],
  "reverse-linked-list": [
    "Amazon",
    "Microsoft"
  ],
  "lowest-common-ancestor-of-a-binary-search-tree": [
    "Amazon",
    "Meta"
  ],
  "merge-k-sorted-lists": [
    "Amazon",
    "Google"
  ],
  "kth-largest-element-in-an-array": [
    "Amazon",
    "Meta"
  ],
  "word-search": [
    "Microsoft",
    "Amazon"
  ],
  "letter-combinations-of-a-phone-number": [
    "Amazon",
    "Google"
  ],
  "permutations": [
    "Amazon",
    "Microsoft"
  ],
  "maximum-depth-of-binary-tree": [
    "Amazon",
    "LinkedIn"
  ],
  "binary-tree-right-side-view": [
    "Meta",
    "Amazon"
  ],
  "construct-binary-tree-from-preorder-and-inorder-traversal": [
    "Amazon",
    "Microsoft"
  ],
  "kth-smallest-element-in-a-bst": [
    "Amazon",
    "Google"
  ],
  "invert-binary-tree": [
    "Google",
    "Amazon"
  ],
  "same-tree": [
    "Amazon"
  ],
  "number-of-islands": [
    "Amazon",
    "Google"
  ],
  "validate-binary-search-tree": [
    "Amazon",
    "Meta"
  ],
  "serialize-and-deserialize-binary-tree": [
    "Amazon",
    "Meta"
  ],
  "word-ladder": [
    "Amazon",
    "Microsoft"
  ],
  "diameter-of-binary-tree": [
    "Meta",
    "Amazon"
  ],
  "binary-tree-zigzag-level-order-traversal": [
    "Amazon",
    "Microsoft"
  ],
  "climbing-stairs": [
    "Amazon",
    "Adobe"
  ],
  "longest-palindromic-substring": [
    "Amazon",
    "Microsoft"
  ],
  "word-break": [
    "Amazon",
    "Meta"
  ],
  "house-robber": [
    "Amazon",
    "LinkedIn"
  ],
  "unique-paths": [
    "Google",
    "Amazon"
  ],
  "best-time-to-buy-and-sell-stock": [
    "Amazon",
    "Meta"
  ],
  "merge-intervals": [
    "Amazon",
    "Bloomberg",
    "Meta"
  ],
  "meeting-rooms": [
    "Amazon",
    "Meta"
  ],
  "rotate-image": [
    "Amazon",
    "Apple"
  ],
  "set-matrix-zeroes": [
    "Amazon",
    "Microsoft"
  ],
  "spiral-matrix": [
    "Amazon",
    "Microsoft"
  ],
  "product-of-array-except-self": [
    "Meta",
    "Amazon"
  ],
  "maximum-subarray": [
    "Microsoft",
    "LinkedIn"
  ],
  "maximum-product-subarray": [
    "Amazon",
    "Google"
  ],
  "sum-of-two-integers": [
    "Meta"
  ],
  "number-of-1-bits": [
    "Apple",
    "Microsoft"
  ],
  "counting-bits": [
    "Amazon"
  ],
  "missing-number": [
    "Amazon",
    "Microsoft"
  ],
  "reverse-bits": [
    "Apple"
  ],
  "longest-increasing-subsequence": [
    "Microsoft",
    "Google"
  ],
  "longest-common-subsequence": [
    "Amazon",
    "Google"
  ],
  "house-robber-ii": [
    "Amazon"
  ],
  "decode-ways": [
    "Meta",
    "Amazon"
  ],
  "jump-game": [
    "Amazon",
    "Microsoft"
  ],
  "clone-graph": [
    "Meta",
    "Google"
  ],
  "pacific-atlantic-water-flow": [
    "Google",
    "Amazon"
  ],
  "longest-consecutive-sequence": [
    "Google",
    "Meta"
  ],
  "graph-valid-tree": [
    "Meta",
    "Google"
  ],
  "number-of-connected-components-in-an-undirected-graph": [
    "Amazon",
    "Google"
  ],
  "insert-interval": [
    "Google",
    "LinkedIn"
  ],
  "non-overlapping-intervals": [
    "Amazon"
  ],
  "meeting-rooms-ii": [
    "Amazon",
    "Google"
  ],
  "reorder-list": [
    "Amazon"
  ],
  "longest-repeating-character-replacement": [
    "Google"
  ],
  "palindromic-substrings": [
    "Amazon"
  ],
  "encode-and-decode-strings": [
    "Google",
    "Meta"
  ],
  "subtree-of-another-tree": [
    "Amazon"
  ],
  "word-search-ii": [
    "Google",
    "Amazon"
  ],
  "top-k-frequent-elements": [
    "Amazon",
    "Meta"
  ],
  "powx-n": [
    "Google",
    "Meta"
  ],
  "longest-common-prefix": [
    "Amazon",
    "Google"
  ],
  "sliding-window-maximum": [
    "Amazon",
    "Google"
  ],
  "decode-string": [
    "Amazon",
    "Google"
  ],
  "koko-eating-bananas": [
    "Amazon",
    "Google"
  ],
  "count-complete-tree-nodes": [
    "Google",
    "Amazon"
  ],
  "find-peak-element": [
    "Amazon",
    "Google"
  ],
  "convert-sorted-array-to-binary-search-tree": [
    "Amazon",
    "Google"
  ],
  "delete-node-in-a-bst": [
    "Amazon",
    "Google"
  ],
  "generate-parentheses": [
    "Amazon",
    "Google"
  ],
  "subsets": [
    "Google",
    "Meta",
    "Amazon"
  ],
  "palindrome-partitioning": [
    "Amazon",
    "Google"
  ],
  "network-delay-time": [
    "Amazon",
    "Google"
  ],
  "redundant-connection": [
    "Amazon",
    "Google"
  ],
  "surrounded-regions": [
    "Amazon",
    "Google"
  ],
  "binary-tree-paths": [
    "Amazon",
    "Google"
  ],
  "binary-tree-preorder-traversal": [
    "Amazon",
    "Google"
  ],
  "swim-in-rising-water": [
    "Amazon",
    "Google"
  ],
  "edit-distance": [
    "Google",
    "Amazon"
  ],
  "burst-balloons": [
    "Amazon",
    "Google"
  ],
  "maximum-profit-in-job-scheduling": [
    "Amazon",
    "Google"
  ],
  "jump-game-ii": [
    "Amazon",
    "Google"
  ],
  "plus-one": [
    "Amazon",
    "Google"
  ],
  "single-number": [
    "Amazon",
    "Google"
  ],
  "ransom-note": [
    "Google"
  ],
  "longest-palindrome": [
    "Amazon"
  ],
  "majority-element": [
    "Amazon",
    "Adobe"
  ],
  "sort-colors": [
    "Amazon",
    "Microsoft"
  ],
  "string-to-integer-atoi": [
    "Amazon",
    "Microsoft"
  ],
  "implement-queue-using-stacks": [
    "Amazon",
    "Microsoft"
  ],
  "middle-of-the-linked-list": [
    "Amazon"
  ],
  "evaluate-reverse-polish-notation": [
    "Amazon",
    "LinkedIn"
  ],
  "lowest-common-ancestor-of-a-binary-tree": [
    "Meta",
    "Amazon"
  ],
  "flood-fill": [
    "Amazon"
  ],
  "rotting-oranges": [
    "Amazon"
  ],
  "minimum-height-trees": [
    "Google",
    "Amazon"
  ],
  "first-bad-version": [
    "Meta",
    "Google"
  ],
  "time-based-key-value-store": [
    "Amazon"
  ],
  "partition-equal-subset-sum": [
    "Amazon"
  ],
  "task-scheduler": [
    "Amazon",
    "Meta"
  ],
  "squares-of-a-sorted-array": [
    "Amazon",
    "Meta",
    "Google"
  ],
  "move-zeroes": [
    "Meta",
    "Amazon"
  ],
  "palindrome-number": [
    "Amazon",
    "Apple"
  ],
  "remove-element": [
    "Amazon",
    "Microsoft"
  ],
  "merge-sorted-array": [
    "Meta",
    "Amazon"
  ],
  "find-all-numbers-disappeared-in-an-array": [
    "Amazon",
    "Google"
  ],
  "intersection-of-two-arrays-ii": [
    "Amazon",
    "Meta"
  ],
  "roman-to-integer": [
    "Amazon",
    "Microsoft"
  ],
  "best-time-to-buy-and-sell-stock-ii": [
    "Amazon",
    "Microsoft"
  ],
  "rotate-array": [
    "Amazon",
    "Microsoft"
  ],
  "subarray-sum-equals-k": [
    "Meta",
    "Amazon"
  ],
  "next-permutation": [
    "Google",
    "Amazon"
  ],
  "two-sum-ii-input-array-is-sorted": [
    "Amazon",
    "Adobe"
  ],
  "remove-duplicates-from-sorted-array": [
    "Amazon",
    "Microsoft"
  ],
  "permutation-in-string": [
    "Amazon",
    "Microsoft"
  ],
  "max-consecutive-ones-iii": [
    "Amazon",
    "Google"
  ],
  "minimum-size-subarray-sum": [
    "Amazon",
    "Google"
  ],
  "next-greater-element-i": [
    "Amazon",
    "Meta"
  ],
  "simplify-path": [
    "Meta",
    "Amazon"
  ],
  "palindrome-linked-list": [
    "Amazon",
    "Meta"
  ],
  "odd-even-linked-list": [
    "Amazon",
    "Microsoft"
  ],
  "sort-list": [
    "Amazon",
    "Microsoft"
  ],
  "symmetric-tree": [
    "Amazon",
    "Microsoft"
  ],
  "path-sum": [
    "Amazon",
    "Microsoft"
  ],
  "count-good-nodes-in-binary-tree": [
    "Amazon",
    "Microsoft"
  ],
  "max-area-of-island": [
    "Amazon",
    "Google"
  ],
  "number-of-provinces": [
    "Amazon",
    "Microsoft"
  ],
  "last-stone-weight": [
    "Amazon"
  ],
  "subsets-ii": [
    "Amazon",
    "Meta"
  ],
  "permutations-ii": [
    "Amazon",
    "Microsoft"
  ],
  "search-insert-position": [
    "Amazon",
    "Microsoft"
  ],
  "min-cost-climbing-stairs": [
    "Amazon",
    "Adobe"
  ],
  "maximal-square": [
    "Amazon",
    "Google"
  ],
  "design-underground-system": [
    "Amazon",
    "Google"
  ],
  "excel-sheet-column-number": [
    "Amazon",
    "Microsoft"
  ],
  "insert-delete-getrandom-o1-duplicates-allowed": [
    "Amazon",
    "Meta"
  ],
  "factorial-trailing-zeroes": [
    "Amazon",
    "Bloomberg"
  ],
  "excel-sheet-column-title": [
    "Amazon",
    "Microsoft"
  ],
  "insert-delete-getrandom-o1": [
    "Amazon",
    "Google",
    "Meta"
  ],
  "integer-to-roman": [
    "Amazon",
    "Microsoft"
  ],
  "integer-to-english-words": [
    "Amazon",
    "Microsoft"
  ],
  "find-pivot-index": [
    "Amazon",
    "Google"
  ],
  "maximum-size-subarray-sum-equals-k": [
    "Meta",
    "Amazon"
  ],
  "max-consecutive-ones": [
    "Amazon"
  ],
  "lfu-cache": [
    "Amazon",
    "Google"
  ],
  "multiply-strings": [
    "Meta",
    "Amazon"
  ],
  "max-points-on-a-line": [
    "Amazon",
    "Google"
  ],
  "pascals-triangle": [
    "Amazon",
    "Apple"
  ],
  "path-sum-iii": [
    "Amazon",
    "Google"
  ],
  "range-sum-query-immutable": [
    "Amazon",
    "Google"
  ],
  "range-sum-query-2d-immutable": [
    "Amazon",
    "Google"
  ],
  "rearrange-array-elements-by-sign": [
    "Amazon"
  ],
  "set-mismatch": [
    "Amazon"
  ],
  "reverse-integer": [
    "Amazon",
    "Apple"
  ],
  "third-maximum-number": [
    "Amazon",
    "Google"
  ],
  "ugly-number": [
    "Amazon"
  ],
  "shortest-unsorted-continuous-subarray": [
    "Amazon",
    "Google"
  ],
  "snapshot-array": [
    "Amazon",
    "Google"
  ],
  "stock-price-fluctuation": [
    "Amazon",
    "Google"
  ],
  "wiggle-sort-ii": [
    "Google",
    "Amazon"
  ],
  "reverse-words-in-a-string": [
    "Amazon",
    "Microsoft"
  ],
  "maximum-nesting-depth-of-the-parentheses": [
    "Amazon"
  ],
  "remove-outermost-parentheses": [
    "Amazon"
  ],
  "zigzag-conversion": [
    "Amazon",
    "Meta"
  ],
  "rotate-string": [
    "Amazon",
    "Google"
  ],
  "k-diff-pairs-in-an-array": [
    "Amazon",
    "Google"
  ],
  "intersection-of-two-arrays": [
    "Amazon",
    "Meta"
  ],
  "isomorphic-strings": [
    "Amazon",
    "LinkedIn",
    "Google"
  ],
  "sum-of-beauty-of-all-substrings": [
    "Amazon"
  ],
  "valid-sudoku": [
    "Amazon",
    "Apple"
  ],
  "word-pattern": [
    "Amazon",
    "Google"
  ],
  "longest-mountain-in-array": [
    "Amazon",
    "Google"
  ],
  "longest-word-in-dictionary-through-deleting": [
    "Google",
    "Amazon"
  ],
  "one-edit-distance": [
    "Meta",
    "Amazon"
  ],
  "reverse-string": [
    "Apple",
    "Amazon"
  ],
  "remove-duplicates-from-sorted-array-ii": [
    "Amazon",
    "Meta"
  ],
  "reverse-vowels-of-a-string": [
    "Amazon",
    "Google"
  ],
  "string-compression": [
    "Amazon",
    "Microsoft"
  ],
  "valid-palindrome-ii": [
    "Meta"
  ],
  "valid-word-abbreviation": [
    "Meta"
  ],
  "grumpy-bookstore-owner": [
    "Amazon"
  ],
  "subarrays-with-k-different-integers": [
    "Amazon",
    "Google"
  ],
  "longest-subarray-of-1s-after-deleting-one-element": [
    "Amazon",
    "Google"
  ],
  "substring-with-concatenation-of-all-words": [
    "Amazon",
    "Google"
  ],
  "maximum-points-you-can-obtain-from-cards": [
    "Amazon",
    "Google"
  ],
  "minimum-number-of-flips-to-make-the-binary-string-alternating": [
    "Amazon"
  ],
  "find-the-smallest-divisor-given-a-threshold": [
    "Amazon"
  ],
  "count-negative-numbers-in-a-sorted-matrix": [
    "Amazon"
  ],
  "kth-smallest-element-in-a-sorted-matrix": [
    "Amazon",
    "Google"
  ],
  "split-array-largest-sum": [
    "Google",
    "Amazon"
  ],
  "magnetic-force-between-two-balls": [
    "Amazon"
  ],
  "maximum-value-at-a-given-index-in-a-bounded-array": [
    "Amazon"
  ],
  "guess-number-higher-or-lower": [
    "Amazon",
    "Google"
  ],
  "minimum-number-of-days-to-make-m-bouquets": [
    "Amazon",
    "Google"
  ],
  "kth-missing-positive-number": [
    "Amazon"
  ],
  "minimum-time-to-complete-trips": [
    "Amazon",
    "Google"
  ],
  "peak-index-in-a-mountain-array": [
    "Amazon",
    "Google"
  ],
  "random-pick-with-weight": [
    "Meta"
  ],
  "sqrtx": [
    "Amazon",
    "Microsoft"
  ],
  "search-a-2d-matrix": [
    "Amazon",
    "Microsoft"
  ],
  "construct-quad-tree": [
    "Amazon",
    "Google"
  ],
  "minimum-difference-between-highest-and-lowest-of-k-scores": [
    "Amazon",
    "Adobe"
  ],
  "count-of-smaller-numbers-after-self": [
    "Google",
    "Amazon"
  ],
  "h-index": [
    "Amazon",
    "Google"
  ],
  "largest-number": [
    "Amazon",
    "Apple"
  ],
  "reverse-pairs": [
    "Google",
    "Amazon"
  ],
  "relative-sort-array": [
    "Amazon"
  ],
  "sort-an-array": [
    "Amazon",
    "Microsoft"
  ],
  "game-of-life": [
    "Amazon",
    "Google"
  ],
  "minimum-cost-to-cut-a-stick": [
    "Amazon",
    "Google"
  ],
  "merge-nodes-in-between-zeros": [
    "Amazon"
  ],
  "remove-linked-list-elements": [
    "Amazon",
    "Microsoft"
  ],
  "partition-list": [
    "Amazon",
    "Microsoft"
  ],
  "remove-duplicates-from-sorted-list-ii": [
    "Amazon",
    "Microsoft"
  ],
  "reverse-linked-list-ii": [
    "Amazon",
    "Microsoft"
  ],
  "rotate-list": [
    "LinkedIn",
    "Amazon",
    "Microsoft"
  ],
  "split-linked-list-in-parts": [
    "Amazon"
  ],
  "swap-nodes-in-pairs": [
    "Microsoft",
    "Amazon"
  ],
  "dota2-senate": [
    "Amazon",
    "Bloomberg"
  ],
  "implement-stack-using-queues": [
    "Amazon",
    "Microsoft"
  ],
  "exclusive-time-of-functions": [
    "Meta",
    "Amazon"
  ],
  "find-the-celebrity": [
    "Meta",
    "Amazon"
  ],
  "maximum-binary-tree": [
    "Amazon",
    "Google"
  ],
  "number-of-recent-calls": [
    "Google",
    "Amazon"
  ],
  "minimum-remove-to-make-valid-parentheses": [
    "Meta"
  ],
  "next-greater-element-ii": [
    "Amazon",
    "Google"
  ],
  "online-stock-span": [
    "Amazon",
    "Bloomberg"
  ],
  "remove-all-adjacent-duplicates-in-string-ii": [
    "Amazon",
    "Google"
  ],
  "remove-k-digits": [
    "Amazon",
    "Google"
  ],
  "score-of-parentheses": [
    "Amazon",
    "Google"
  ],
  "sum-of-subarray-minimums": [
    "Amazon",
    "Google"
  ],
  "ipo": [
    "Amazon",
    "Google"
  ],
  "maximum-number-of-events-that-can-be-attended": [
    "Amazon",
    "Google"
  ],
  "minimum-cost-to-connect-sticks": [
    "Amazon"
  ],
  "reorganize-string": [
    "Amazon"
  ],
  "the-k-weakest-rows-in-a-matrix": [
    "Amazon",
    "Google"
  ],
  "minimum-number-of-refueling-stops": [
    "Amazon",
    "Google"
  ],
  "seat-reservation-manager": [
    "Amazon"
  ],
  "the-skyline-problem": [
    "Amazon",
    "Google"
  ],
  "single-threaded-cpu": [
    "Amazon",
    "Google"
  ],
  "sort-characters-by-frequency": [
    "Amazon",
    "Google"
  ],
  "ugly-number-ii": [
    "Amazon",
    "Microsoft"
  ],
  "binary-tree-postorder-traversal": [
    "Amazon",
    "Meta"
  ],
  "binary-tree-vertical-order-traversal": [
    "Meta",
    "Amazon"
  ],
  "longest-cycle-in-a-graph": [
    "Amazon",
    "Google"
  ],
  "boundary-of-binary-tree": [
    "Amazon",
    "Meta"
  ],
  "closest-binary-search-tree-value": [
    "Meta",
    "Amazon"
  ],
  "construct-binary-search-tree-from-preorder-traversal": [
    "Amazon",
    "Meta"
  ],
  "construct-binary-tree-from-inorder-and-postorder-traversal": [
    "Amazon",
    "Microsoft"
  ],
  "convert-binary-search-tree-to-sorted-doubly-linked-list": [
    "Meta",
    "Amazon"
  ],
  "convert-bst-to-greater-tree": [
    "Amazon",
    "Google"
  ],
  "vertical-order-traversal-of-a-binary-tree": [
    "Amazon",
    "Meta"
  ],
  "find-mode-in-binary-search-tree": [
    "Amazon",
    "Google"
  ],
  "distribute-coins-in-binary-tree": [
    "Google",
    "Amazon"
  ],
  "find-duplicate-subtrees": [
    "Amazon",
    "Google"
  ],
  "flatten-a-multilevel-doubly-linked-list": [
    "Amazon",
    "Bloomberg"
  ],
  "flatten-binary-tree-to-linked-list": [
    "Microsoft",
    "Amazon"
  ],
  "inorder-successor-in-bst": [
    "Meta",
    "Amazon"
  ],
  "word-ladder-ii": [
    "Amazon",
    "Google"
  ],
  "insert-into-a-binary-search-tree": [
    "Amazon",
    "Microsoft"
  ],
  "minimum-absolute-difference-in-bst": [
    "Amazon",
    "Google"
  ],
  "is-graph-bipartite": [
    "Amazon",
    "Google"
  ],
  "jump-game-iii": [
    "Amazon",
    "Google"
  ],
  "minimum-depth-of-binary-tree": [
    "Amazon",
    "Microsoft"
  ],
  "keys-and-rooms": [
    "Amazon",
    "Google"
  ],
  "minimum-distance-between-bst-nodes": [
    "Google",
    "Amazon"
  ],
  "largest-bst-subtree": [
    "Amazon",
    "Microsoft"
  ],
  "range-sum-of-bst": [
    "Meta",
    "Amazon"
  ],
  "maximum-width-of-binary-tree": [
    "Amazon",
    "Google"
  ],
  "maximum-xor-with-an-element-from-array": [
    "Amazon",
    "Google"
  ],
  "implement-trie-ii-prefix-tree": [
    "Amazon",
    "Google"
  ],
  "longest-word-in-dictionary": [
    "Amazon",
    "Google"
  ],
  "prefix-and-suffix-search": [
    "Amazon",
    "Google"
  ],
  "map-sum-pairs": [
    "Amazon",
    "Google"
  ],
  "stream-of-characters": [
    "Amazon",
    "Google"
  ],
  "maximum-xor-of-two-numbers-in-an-array": [
    "Amazon",
    "Google"
  ],
  "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance": [
    "Amazon"
  ],
  "find-the-duplicate-number": [
    "Amazon",
    "Microsoft",
    "Adobe"
  ],
  "making-a-large-island": [
    "Amazon",
    "Google"
  ],
  "most-stones-removed-with-same-row-or-column": [
    "Amazon",
    "Google"
  ],
  "number-of-ways-to-arrive-at-destination": [
    "Amazon",
    "Google"
  ],
  "path-with-minimum-effort": [
    "Amazon",
    "Google"
  ],
  "satisfiability-of-equality-equations": [
    "Amazon",
    "Google"
  ],
  "n-queens-ii": [
    "Amazon",
    "Google"
  ],
  "letter-case-permutation": [
    "Amazon",
    "Google"
  ],
  "permutation-sequence": [
    "Amazon",
    "Google"
  ],
  "matchsticks-to-square": [
    "Amazon",
    "Google"
  ],
  "sudoku-solver": [
    "Amazon",
    "Uber"
  ],
  "partition-to-k-equal-sum-subsets": [
    "Amazon",
    "Google"
  ],
  "word-break-ii": [
    "Amazon",
    "Google"
  ],
  "path-sum-ii": [
    "Amazon",
    "Microsoft"
  ],
  "restore-ip-addresses": [
    "Amazon",
    "Google"
  ],
  "count-square-submatrices-with-all-ones": [
    "Amazon",
    "Google"
  ],
  "delete-and-earn": [
    "Amazon",
    "Google"
  ],
  "cherry-pickup-ii": [
    "Amazon",
    "Google"
  ],
  "distinct-subsequences": [
    "Amazon",
    "Google"
  ],
  "house-robber-iii": [
    "Amazon",
    "Google"
  ],
  "integer-break": [
    "Amazon"
  ],
  "frog-jump": [
    "Amazon",
    "Google"
  ],
  "interleaving-string": [
    "Amazon",
    "Google"
  ],
  "knight-dialer": [
    "Amazon",
    "Google"
  ],
  "longest-increasing-path-in-a-matrix": [
    "Google",
    "Amazon"
  ],
  "last-stone-weight-ii": [
    "Amazon",
    "Google"
  ],
  "longest-arithmetic-subsequence": [
    "Amazon",
    "Google"
  ],
  "maximal-rectangle": [
    "Google",
    "Amazon"
  ],
  "longest-palindromic-subsequence": [
    "Amazon",
    "Google"
  ],
  "minimum-difficulty-of-a-job-schedule": [
    "Amazon",
    "Google"
  ],
  "longest-string-chain": [
    "Amazon",
    "Google"
  ],
  "palindrome-partitioning-ii": [
    "Amazon",
    "Google"
  ],
  "maximum-length-of-pair-chain": [
    "Amazon",
    "Google"
  ],
  "regular-expression-matching": [
    "Meta",
    "Google"
  ],
  "russian-doll-envelopes": [
    "Amazon",
    "Google"
  ],
  "maximum-subarray-sum-with-one-deletion": [
    "Amazon"
  ],
  "maximum-sum-circular-subarray": [
    "Amazon",
    "Google"
  ],
  "shortest-common-supersequence": [
    "Amazon",
    "Google"
  ],
  "minimum-falling-path-sum": [
    "Amazon"
  ],
  "super-egg-drop": [
    "Google",
    "Amazon"
  ],
  "minimum-path-sum": [
    "Amazon",
    "Google"
  ],
  "number-of-dice-rolls-with-target-sum": [
    "Amazon",
    "Google"
  ],
  "wildcard-matching": [
    "Amazon",
    "Google"
  ],
  "number-of-longest-increasing-subsequence": [
    "Amazon",
    "Google"
  ],
  "ones-and-zeroes": [
    "Amazon",
    "Google"
  ],
  "partition-array-for-maximum-sum": [
    "Amazon",
    "Google"
  ],
  "perfect-squares": [
    "Amazon",
    "Google"
  ],
  "predict-the-winner": [
    "Amazon",
    "Google"
  ],
  "stone-game": [
    "Amazon",
    "Google"
  ],
  "target-sum": [
    "Meta",
    "Amazon"
  ],
  "triangle": [
    "Amazon",
    "Google"
  ],
  "unique-binary-search-trees": [
    "Amazon",
    "Google"
  ],
  "unique-paths-ii": [
    "Amazon",
    "Google"
  ],
  "assign-cookies": [
    "Amazon"
  ],
  "boats-to-save-people": [
    "Amazon",
    "Google"
  ],
  "gas-station": [
    "Amazon",
    "Meta",
    "Google"
  ],
  "binary-tree-cameras": [
    "Google",
    "Amazon"
  ],
  "hand-of-straights": [
    "Google",
    "Amazon"
  ],
  "candy": [
    "Google",
    "Amazon"
  ],
  "merge-triplets-to-form-target-triplet": [
    "Amazon"
  ],
  "lemonade-change": [
    "Amazon"
  ],
  "minimum-add-to-make-parentheses-valid": [
    "Amazon",
    "Google"
  ],
  "partition-labels": [
    "Amazon",
    "Meta"
  ],
  "car-pooling": [
    "Amazon",
    "Google"
  ],
  "employee-free-time": [
    "Amazon",
    "Google"
  ],
  "interval-list-intersections": [
    "Meta",
    "Amazon"
  ],
  "minimum-interval-to-include-each-query": [
    "Amazon",
    "Google"
  ],
  "summary-ranges": [
    "Amazon",
    "Google"
  ],
  "minimum-number-of-arrows-to-burst-balloons": [
    "Amazon",
    "Google"
  ],
  "bitwise-and-of-numbers-range": [
    "Amazon",
    "Google"
  ],
  "minimum-bit-flips-to-convert-number": [
    "Amazon"
  ],
  "divide-two-integers": [
    "Amazon",
    "Microsoft"
  ],
  "gray-code": [
    "Amazon",
    "Google"
  ],
  "number-complement": [
    "Amazon",
    "Google"
  ],
  "single-number-ii": [
    "Amazon",
    "Google"
  ],
  "single-number-iii": [
    "Amazon"
  ],
  "power-of-two": [
    "Amazon",
    "Google"
  ],
  "total-hamming-distance": [
    "Amazon"
  ],
  "count-and-say": [
    "Meta",
    "Amazon"
  ],
  "two-sum-iv-input-is-a-bst": [
    "Amazon",
    "Meta"
  ],
  "valid-parenthesis-string": [
    "Amazon",
    "Meta"
  ],
  "walls-and-gates": [
    "Meta",
    "Amazon"
  ],
  "min-cost-to-connect-all-points": [
    "Amazon",
    "Google"
  ],
  "reconstruct-itinerary": [
    "Amazon",
    "Google"
  ],
  "happy-number": [
    "Amazon",
    "Google"
  ],
  "count-good-numbers": [
    "Amazon"
  ],
  "delete-the-middle-node-of-a-linked-list": [
    "Amazon"
  ],
  "longest-duplicate-substring": [
    "Google",
    "Amazon"
  ],
  "majority-element-ii": [
    "Amazon",
    "Google"
  ],
  "search-a-2d-matrix-ii": [
    "Amazon",
    "Google"
  ],
  "search-in-rotated-sorted-array-ii": [
    "Amazon",
    "Microsoft"
  ],
  "single-element-in-a-sorted-array": [
    "Amazon",
    "Meta"
  ],
  "linked-list-cycle-ii": [
    "Amazon",
    "Microsoft"
  ],
  "number-of-substrings-containing-all-three-characters": [
    "Amazon"
  ],
  "search-in-a-binary-search-tree": [
    "Amazon"
  ],
  "recover-binary-search-tree": [
    "Amazon",
    "Meta"
  ],
  "number-of-enclaves": [
    "Amazon",
    "Google"
  ],
  "number-of-distinct-islands": [
    "Amazon",
    "Meta"
  ],
  "replace-words": [
    "Amazon",
    "Google"
  ],
  "repeated-substring-pattern": [
    "Amazon",
    "Google"
  ],
  "repeated-string-match": [
    "Google",
    "Amazon"
  ],
  "shortest-palindrome": [
    "Google",
    "Amazon"
  ],
  "populating-next-right-pointers-in-each-node": [
    "Meta",
    "Amazon"
  ],
  "trim-a-binary-search-tree": [
    "Amazon"
  ],
  "populating-next-right-pointers-in-each-node-ii": [
    "Meta",
    "Amazon"
  ],
  "sum-root-to-leaf-numbers": [
    "Amazon",
    "Meta"
  ],
  "snakes-and-ladders": [
    "Amazon",
    "Google"
  ],
  "minimum-genetic-mutation": [
    "Amazon",
    "Google"
  ]
};
